---
title: "Idaho Pines Mortality Analysis"
output:
  html_document: default
  pdf_document: default
date: "2024-11-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries:

```{r, message = FALSE}
library(ggmap)
library(readr)
library(ggmap)
library(viridis)
library(spmodel)
library(sf)
library(tidyr)
library(tigris)
library(dplyr)
```

Get data/maps:

```{r, message = FALSE}
#Read in FIA data
pines <- read_csv("data/pines_plotsdat.csv")

#Remove any datapoints that we can't use due to NA values for predictor variables
pines <- pines %>% drop_na(BALIVE)

#Create binary presence/absence columns for agent classes of primary disturbance codes
pines$INSECT <- ifelse(pines$DSTRBCD1 >= 10 & pines$DSTRBCD1 <= 12, 1, 0)
pines$DISEASE <- ifelse(pines$DSTRBCD1 >= 20 & pines$DSTRBCD1 <= 22, 1, 0)
pines$FIRE <- ifelse(pines$DSTRBCD1 >= 30 & pines$DSTRBCD1 <= 32, 1, 0)

#Get map for all of Idaho
idaho_bbox <- c(-117.25,41.9,-110.95,49.05)
idaho_map <- get_stadiamap(bbox = idaho_bbox, zoom = 7)

#Get map focused on area of study
forest_bbox <- c(-117.25,45,-114,47.5)
forest_map <- get_stadiamap(bbox = forest_bbox, zoom = 9)

#Convert pines dataset to sf object with CRS for NAD83/Idaho Transverse Mercator
pines_sf <- st_as_sf(pines, coords = c("LON", "LAT"), crs = 8826)

#Reading in statewide climate data so we can make predictions later on
idaho_clim <- read_csv("data/precip_idaho.csv")
idaho_temp <- read_csv("data/temp_idaho.csv")
idaho_clim$temp <- idaho_temp$tmean

#Convert dataset to sf object with same CRS as pines_sf
idaho_clim_sf <- st_as_sf(idaho_clim, coords = c("x", "y"), crs = 8826)
```

Plots for exploration/visual assessment:

```{r}
api_key <- "097faf3b-452d-43dc-bb79-71f676e986be"
register_google(key = api_key)
```

```{r}
bbox <- c(left = -116.4615, bottom = 42.0000, right = -111.0437, top = 49.0000)
forest_map <- get_stadiamap(bbox = bbox, zoom = 6, maptype = "stamen_terrain") # Load the state boundary for 

nez_perce_clearwater_bbox <- c(left = -117.0, bottom = 45.0, right = -114.0, top = 47.5)
nezperece_clearwater_map <- get_stadiamap(bbox = nez_perce_clearwater_bbox, zoom = 7)

ID_state <- tigris::states() %>% filter(STATEFP == "16") %>% st_transform(crs = st_crs(4326)) %>% st_as_sf()

#Plot locations
ggmap(idaho_map) +
  geom_point(aes(x = LON, y = LAT), data = data.frame(pines)) +
  geom_sf(data = ID_state, inherit.aes = FALSE, fill = NA, color = "black", size = 1.5) +  # Increase size for bolder border
  scale_color_viridis(option = "inferno", direction = -1, name = "Dead Proportion") +
  labs(title = "Plot Locations", x = "Longitude", y = "Latitude", color = "Dead Proportion", size = "Dead Proportion") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7) 
  )

#Dead proportion of trees
ggmap(nezperece_clearwater_map) + 
  geom_point(aes(x = LON, y = LAT, color = DEADPROP, size = DEADPROP), data = pines) +
  geom_sf(data = ID_state, inherit.aes = FALSE, fill = NA, color = "black", size = 0.5) + 
  scale_color_viridis(option = "inferno", direction = -1, name = "Dead Proportion") +
  labs(title = "Proportion of Dead Trees", x = "Longitude", y = "Latitude", color = "Dead Proportion", size = "Dead Proportion") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7) 
  )

#Proportion of dead trees by Temperature
ggmap(idaho_map) +
  geom_point(aes(x = LON, y = LAT, color = temp, size = DEADPROP), data = data.frame(pines))  +
  geom_sf(data = ID_state, inherit.aes = FALSE, fill = NA, color = "black", size = 0.5) + 
  scale_color_viridis(option = "rocket", direction = -1) +
  labs(title = "Proportion of Dead Trees by Temperature", x = "Longitude", y = "Latitude", color = "Dead Proportion", size = "Dead Proportion") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7) 
  )

#Proportion of dead trees by Precipitation
ggmap(idaho_map) +
  geom_point(aes(x = LON, y = LAT, color = precip, size = DEADPROP), data = data.frame(pines))  +
  geom_sf(data = ID_state, inherit.aes = FALSE, fill = NA, color = "black", size = 0.5) + 
  scale_color_viridis(direction = -1) +
    labs(title = "Proportion of Dead Trees by Precipitation", x = "Longitude", y = "Latitude", color = "Dead Proportion", size = "Dead Proportion") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7) 
  )

#Proportion of dead trees by competition
ggmap(idaho_map) +
  geom_point(aes(x = LON, y = LAT, color = BALIVE, size = DEADPROP), data = data.frame(pines))  +
  geom_sf(data = ID_state, inherit.aes = FALSE, fill = NA, color = "black", size = 0.5) + 
  scale_color_viridis(option = "mako", direction = -1) +
  labs(title = "Proportion of Dead Trees by Competition", x = "Longitude", y = "Latitude", color = "Dead Proportion", size = "Dead Proportion") + 
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 7),
    axis.text.y = element_text(size = 7) 
  )
```

```{r}
#Simple statewide map to orient the project
ggmap(idaho_map) +
  geom_point(aes(x = LON, y = LAT), data = data.frame(pines))

#Points sized/colored by proportion dead
ggmap(forest_map) +
  geom_point(aes(x = LON, y = LAT, color = DEADPROP, size = DEADPROP), data = data.frame(pines))  +
  scale_color_viridis(option = "inferno", direction = -1) 

#Size data points by proportion dead, color by temp
ggmap(forest_map) +
  geom_point(aes(x = LON, y = LAT, color = temp, size = DEADPROP), data = data.frame(pines))  +
  scale_color_viridis(option = "rocket", direction = -1) 

#Size data points by proportion dead, color by precip
ggmap(forest_map) +
  geom_point(aes(x = LON, y = LAT, color = precip, size = DEADPROP), data = data.frame(pines))  +
  scale_color_viridis(direction = -1) 

#Plot agent data

#Size data points by proportion dead, color by competition
ggmap(forest_map) +
  geom_point(aes(x = LON, y = LAT, color = BALIVE, size = DEADPROP), data = data.frame(pines))  +
  scale_color_viridis(option = "mako", direction = -1) 
```
Data transformation into logit space:

```{r}
#Since we need to limit our response variable to between 0 and 1, define some transformations 
logit <- function(x) log(x / (1 - x))
expit <- function(x) 1 / (1 + exp(-x))

#Transforming data so we can work in the transformed space without infinite values, see generalized_response slides page 31
pines_sf$DEADPROP_adj <- pines_sf$DEADPROP
#Replace observations of none dead with 0.01
pines_sf$DEADPROP_adj[pines_sf$DEADPROP == 0] <- 0.01
#Replace observations of all dead with 0.99
pines_sf$DEADPROP_adj[pines_sf$DEADPROP == 1] <- 0.99

#Transform data into new column
pines_sf$logit_DEADPROP_adj <- logit(pines_sf$DEADPROP_adj)
```

Define formulas for model fitting:

```{r}
#MAT and MAP formula with and without interactions
logit_climate_formula <- logit_DEADPROP_adj ~ precip * temp
logit_climate_formula_noi <- logit_DEADPROP_adj ~ precip + temp

#Intercept-only model
intercept_formula_transform <- logit_DEADPROP ~ 1
intercept_formula <- DEADPROP ~ 1

#Competition
competition_formula_transform <- logit_DEADPROP_adj ~ BALIVE
competition_formula <- DEADPROP_adj ~ BALIVE

#Fire, insect, disease without interactions
dist_formula_transform <- logit_DEADPROP_adj ~ FIRE + INSECT + DISEASE
dist_formula <- DEADPROP_adj ~ FIRE + INSECT + DISEASE

#Combined model
combined_formula_transform <- logit_DEADPROP_adj ~ BALIVE + FIRE + INSECT + DISEASE + precip + temp
combined_formula <- DEADPROP_adj ~ BALIVE + FIRE + INSECT + DISEASE + precip + temp
```

Model fitting:

```{r}
#Let's turn this section into a function so that we don't have to redo it all manually

#Playing around with fitting models to the dataset just for climate variables for now

#Transformed response, see generalized_response slides page 32
fit_climate_transform_exp <- splm(logit_climate_formula, data = pines_sf, spcov_type = "exponential",
estmethod = "sv-wls")
summary(fit_climate_transform_exp)
confint(fit_climate_transform_exp)
#Our confint here covers zero for everything except temperature with the no interaction formula

#Beta, no spatial covariance, see generalized_response slides page 35
climate_formula <- DEADPROP_adj ~ precip * temp
fit_climate_beta <- spglm(climate_formula, data = pines_sf, family = beta, spcov_type = "none")

#GLM with beta response, see generalized_response slides page 36
fit_climate_beta_mat <- spglm(climate_formula, data = pines_sf, family = beta,
  spcov_initial = spcov_initial("matern", extra = 2, known = "extra"))
fit_climate_beta_exp <- spglm(climate_formula, data = pines_sf, family = beta,
spcov_type = "exponential")

#Make some predictions based on scaled and centered climate data
idaho_clim_sf$pred_beta_matern <- predict(fit_climate_beta_mat, newdata = idaho_clim_sf, type = "response")

#Plot of predictions based on beta matern model
plot(idaho_clim_sf["pred_beta_matern"], key.pos = 1, axes = TRUE, key.width = lcm(1.3), key.length = 1.0)
```

Model diagnostics:

```{r}
#Put residual plots here


#Climate only diagnostics
AIC(fit_climate_beta, fit_climate_beta_exp, fit_climate_beta_mat)

t(sapply(list(
  "beta" = fit_climate_beta,
  "beta exp" = fit_climate_beta_exp,
  "beta mat" = fit_climate_beta_mat
), function(x) loocv(x)[, 1:3]))
```
